runtime: python
env: flex

entrypoint: gunicorn application:application -b :8080 --timeout 120 --log-level debug

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 25
